\('(.+)', '.+', '([-\.\d]+)', '([-\.\d]+)', NULL, NULL\),
UPDATE countries SET longitude=$2, latitude=$3 WHERE ISO_code='$1';

INSERT INTO `countries` (`ISO_code`, `name`, `longitude`, `latitude`, `created_at`, `updated_at`) VALUES
	UPDATE countries SET longitude=-69.968338, latitude=12.52111 WHERE ISO_code='ABW';
	UPDATE countries SET longitude=67.709953, latitude=33.93911 WHERE ISO_code='AFG';
	UPDATE countries SET longitude=17.873887, latitude=-11.202692 WHERE ISO_code='AGO';
	UPDATE countries SET longitude=-63.068615, latitude=18.220554 WHERE ISO_code='AIA';
	('ALA', 'Aland Islands', '', '', NULL, NULL),
	UPDATE countries SET longitude=20.168331, latitude=41.153332 WHERE ISO_code='ALB';
	UPDATE countries SET longitude=1.601554, latitude=42.546245 WHERE ISO_code='AND';
	UPDATE countries SET longitude=53.847818, latitude=23.424076 WHERE ISO_code='ARE';
	UPDATE countries SET longitude=-63.616672, latitude=-38.416097 WHERE ISO_code='ARG';
	UPDATE countries SET longitude=45.038189, latitude=40.069099 WHERE ISO_code='ARM';
	UPDATE countries SET longitude=-170.132217, latitude=-14.270972 WHERE ISO_code='ASM';
	UPDATE countries SET longitude=-0.071389, latitude=-75.250973 WHERE ISO_code='ATA';
	UPDATE countries SET longitude=69.348557, latitude=-49.280366 WHERE ISO_code='ATF';
	UPDATE countries SET longitude=-61.796428, latitude=17.060816 WHERE ISO_code='ATG';
	UPDATE countries SET longitude=133.775136, latitude=-25.274398 WHERE ISO_code='AUS';
	UPDATE countries SET longitude=14.550072, latitude=47.516231 WHERE ISO_code='AUT';
	UPDATE countries SET longitude=47.576927, latitude=40.143105 WHERE ISO_code='AZE';
	('BDI', 'Burundi', '29.918886', '-3.373056	', NULL, NULL),
	UPDATE countries SET longitude=4.469936, latitude=50.503887 WHERE ISO_code='BEL';
	UPDATE countries SET longitude=2.315834, latitude=9.30769 WHERE ISO_code='BEN';
	('BES', 'Bonaire', '5', '', NULL, NULL),
	UPDATE countries SET longitude=-1.561593, latitude=12.238333 WHERE ISO_code='BFA';
	UPDATE countries SET longitude=23.684994, latitude=90.356331 WHERE ISO_code='BGD';
	UPDATE countries SET longitude=25.48583, latitude=42.733883 WHERE ISO_code='BGR';
	UPDATE countries SET longitude=50.637772, latitude=25.930414 WHERE ISO_code='BHR';
	UPDATE countries SET longitude=-77.39628, latitude=25.03428 WHERE ISO_code='BHS';
	UPDATE countries SET longitude=17.679076, latitude=43.915886 WHERE ISO_code='BIH';
	('BLM', 'Saint Barthélemy', '', '', NULL, NULL),
	('BLR', 'Belarus', '', '', NULL, NULL),
	('BLZ', 'Belize', '', '', NULL, NULL),
	UPDATE countries SET longitude=-64.75737, latitude=32.321384 WHERE ISO_code='BMU';
	UPDATE countries SET longitude=-63.588653, latitude=-16.290154 WHERE ISO_code='BOL';
	('BRA', 'Brazil', '', '', NULL, NULL),
	('BRB', 'Barbados', '', '', NULL, NULL),
	('BRN', 'Brunei', '', '', NULL, NULL),
	('BTN', 'Bhutan', '', '', NULL, NULL),
	('BVT', 'Bouvet Island', '', '', NULL, NULL),
	('BWA', 'Botswana', '', '', NULL, NULL),
	('CAF', 'Central African Republic', '', '', NULL, NULL),
	('CAN', 'Canada', '', '', NULL, NULL),
	('CCK', 'Cocos (Keeling) Islands', '', '', NULL, NULL),
	('CHE', 'Switzerland', '', '', NULL, NULL),
	('CHL', 'Chile', '', '', NULL, NULL),
	('CHN', 'China', '', '', NULL, NULL),
	('CIV', 'Côte d\'Ivoire', '', '', NULL, NULL),
	('CMR', 'Cameroon', '', '', NULL, NULL),
	('COD', 'Democratic Republic of the Congo', '', '', NULL, NULL),
	('COG', 'Republic of the Congo', '', '', NULL, NULL),
	('COK', 'Cook Islands', '', '', NULL, NULL),
	('COL', 'Colombia', '', '', NULL, NULL),
	('COM', 'Comoros', '', '', NULL, NULL),
	('CPV', 'Cape Verde', '', '', NULL, NULL),
	('CRI', 'Costa Rica', '', '', NULL, NULL),
	('CUB', 'Cuba', '', '', NULL, NULL),
	('CUW', 'Curaçao', '', '', NULL, NULL),
	('CXR', 'Christmas Island', '', '', NULL, NULL),
	('CYM', 'Cayman Islands', '', '', NULL, NULL),
	('CYP', 'Cyprus', '', '', NULL, NULL),
	('CZE', 'Czech Republic', '', '', NULL, NULL),
	('DEU', 'Germany', '', '', NULL, NULL),
	('DJI', 'Djibouti', '', '', NULL, NULL),
	('DMA', 'Dominica', '', '', NULL, NULL),
	('DNK', 'Denmark', '', '', NULL, NULL),
	('DOM', 'Dominican Republic', '', '', NULL, NULL),
	('DZA', 'Algeria', '', '', NULL, NULL),
	('ECU', 'Ecuador', '', '', NULL, NULL),
	('EGY', 'Egypt', '', '', NULL, NULL),
	('ERI', 'Eritrea', '', '', NULL, NULL),
	('ESH', 'Western Sahara ', '', '', NULL, NULL),
	('ESP', 'Spain', '', '', NULL, NULL),
	('EST', 'Estonia', '', '', NULL, NULL),
	('ETH', 'Ethiopia', '', '', NULL, NULL),
	('FIN', 'Finland', '', '', NULL, NULL),
	('FJI', 'Fiji', '', '', NULL, NULL),
	('FLK', 'Falkland Islands', '', '', NULL, NULL),
	('FRA', 'France', '', '', NULL, NULL),
	('FRO', 'Faroe Islands', '', '', NULL, NULL),
	('FSM', 'Micronesia', '', '', NULL, NULL),
	('GAB', 'Gabon', '', '', NULL, NULL),
	('GBR', 'United Kingdom', '', '', NULL, NULL),
	('GEO', 'Georgia', '', '', NULL, NULL),
	('GGY', 'Guernsey', '', '', NULL, NULL),
	('GHA', 'Ghana', '', '', NULL, NULL),
	('GIB', 'Gibraltar', '', '', NULL, NULL),
	('GIN', 'Guinea', '', '', NULL, NULL),
	('GLP', 'Guadeloupe', '', '', NULL, NULL),
	('GMB', 'The Gambia', '', '', NULL, NULL),
	('GNB', 'Guinea-Bissau', '', '', NULL, NULL),
	('GNQ', 'Equatorial Guinea', '', '', NULL, NULL),
	('GRC', 'Greece', '', '', NULL, NULL),
	('GRD', 'Grenada', '', '', NULL, NULL),
	('GRL', 'Greenland', '', '', NULL, NULL),
	('GTM', 'Guatemala', '', '', NULL, NULL),
	('GUF', 'French Guiana', '', '', NULL, NULL),
	('GUM', 'Guam', '', '', NULL, NULL),
	('GUY', 'Guyana', '', '', NULL, NULL),
	('HKG', 'Hong Kong', '', '', NULL, NULL),
	('HMD', 'Heard Island and McDonald Islands', '', '', NULL, NULL),
	('HND', 'Honduras', '', '', NULL, NULL),
	('HRV', 'Croatia', '', '', NULL, NULL),
	('HTI', 'Haiti', '', '', NULL, NULL),
	('HUN', 'Hungary', '', '', NULL, NULL),
	('IDN', 'Indonesia', '', '', NULL, NULL),
	('IMN', 'Isle of Man', '', '', NULL, NULL),
	('IND', 'India', '', '', NULL, NULL),
	('IOT', 'British Indian Ocean Territory', '', '', NULL, NULL),
	('IRL', 'Ireland', '', '', NULL, NULL),
	('IRN', 'Iran', '', '', NULL, NULL),
	('IRQ', 'Iraq', '', '', NULL, NULL),
	('ISL', 'Iceland', '', '', NULL, NULL),
	('ISR', 'Israel', '', '', NULL, NULL),
	('ITA', 'Italy', '', '', NULL, NULL),
	('JAM', 'Jamaica', '', '', NULL, NULL),
	('JEY', 'Jersey', '', '', NULL, NULL),
	('JOR', 'Jordan', '', '', NULL, NULL),
	('JPN', 'Japan', '', '', NULL, NULL),
	('KAZ', 'Kazakhstan', '', '', NULL, NULL),
	('KEN', 'Kenya', '', '', NULL, NULL),
	('KGZ', 'Kyrgyzstan', '', '', NULL, NULL),
	('KHM', 'Cambodia', '', '', NULL, NULL),
	('KIR', 'Kiribati', '', '', NULL, NULL),
	('KNA', 'Saint Kitts and Nevis', '', '', NULL, NULL),
	('KOR', 'Republic of Korea', '', '', NULL, NULL),
	('KWT', 'Kuwait', '', '', NULL, NULL),
	('LAO', 'Laos', '', '', NULL, NULL),
	('LBN', 'Lebanon', '', '', NULL, NULL),
	('LBR', 'Liberia', '', '', NULL, NULL),
	('LBY', 'Libya', '', '', NULL, NULL),
	('LCA', 'Saint Lucia', '', '', NULL, NULL),
	('LIE', 'Liechtenstein', '', '', NULL, NULL),
	('LKA', 'Sri Lanka', '', '', NULL, NULL),
	('LSO', 'Lesotho', '', '', NULL, NULL),
	('LTU', 'Lithuania', '', '', NULL, NULL),
	('LUX', 'Luxembourg', '', '', NULL, NULL),
	('LVA', 'Latvia', '', '', NULL, NULL),
	('MAC', 'Macau', '', '', NULL, NULL),
	('MAF', 'Saint Martin (French part)', '', '', NULL, NULL),
	('MAR', 'Morocco', '', '', NULL, NULL),
	('MCO', 'Monaco', '', '', NULL, NULL),
	('MDA', 'Moldova', '', '', NULL, NULL),
	('MDG', 'Madagascar', '', '', NULL, NULL),
	('MDV', 'Maldives', '', '', NULL, NULL),
	('MEX', 'Mexico', '', '', NULL, NULL),
	('MHL', 'Marshall Islands', '', '', NULL, NULL),
	('MKD', 'North Macedonia', '', '', NULL, NULL),
	('MLI', 'Mali', '', '', NULL, NULL),
	('MLT', 'Malta', '', '', NULL, NULL),
	('MMR', 'Myanmar ', '', '', NULL, NULL),
	('MNE', 'Montenegro', '', '', NULL, NULL),
	('MNG', 'Mongolia', '', '', NULL, NULL),
	('MNP', 'Northern Mariana Islands', '', '', NULL, NULL),
	('MOZ', 'Mozambique', '', '', NULL, NULL),
	('MRT', 'Mauritania', '', '', NULL, NULL),
	('MSR', 'Montserrat', '', '', NULL, NULL),
	('MTQ', 'Martinique', '', '', NULL, NULL),
	('MUS', 'Mauritius', '', '', NULL, NULL),
	('MWI', 'Malawi', '', '', NULL, NULL),
	('MYS', 'Malaysia', '', '', NULL, NULL),
	('MYT', 'Mayotte', '', '', NULL, NULL),
	('NAM', 'Namibia', '', '', NULL, NULL),
	('NCL', 'New Caledonia', '', '', NULL, NULL),
	('NER', 'Niger', '', '', NULL, NULL),
	('NFK', 'Norfolk Island', '', '', NULL, NULL),
	('NGA', 'Nigeria', '', '', NULL, NULL),
	('NIC', 'Nicaragua', '', '', NULL, NULL),
	('NIU', 'Niue', '', '', NULL, NULL),
	('NLD', 'Netherlands', '', '', NULL, NULL),
	('NOR', 'Norway', '', '', NULL, NULL),
	('NPL', 'Nepal', '', '', NULL, NULL),
	('NRU', 'Nauru', '', '', NULL, NULL),
	('NZL', 'New Zealand', '', '', NULL, NULL),
	('OMN', 'Oman', '', '', NULL, NULL),
	('PAK', 'Pakistan', '', '', NULL, NULL),
	('PAN', 'Panama', '', '', NULL, NULL),
	('PCN', 'Pitcairn Islands', '', '', NULL, NULL),
	('PER', 'Peru', '', '', NULL, NULL),
	('PHL', 'Philippines', '', '', NULL, NULL),
	('PLW', 'Palau', '', '', NULL, NULL),
	('PNG', 'Papua New Guinea', '', '', NULL, NULL),
	('POL', 'Poland', '', '', NULL, NULL),
	('PRI', 'Puerto Rico', '', '', NULL, NULL),
	('PRK', 'Democratic People\'s Republic of Korea', '', '', NULL, NULL),
	('PRT', 'Portugal', '', '', NULL, NULL),
	('PRY', 'Paraguay', '', '', NULL, NULL),
	('PSE', 'State of Palestine', '', '', NULL, NULL),
	('PYF', 'French Polynesia', '', '', NULL, NULL),
	('QAT', 'Qatar', '', '', NULL, NULL),
	('REU', 'Réunion', '', '', NULL, NULL),
	('ROU', 'Romania', '', '', NULL, NULL),
	('RUS', 'Russian Federation', '', '', NULL, NULL),
	('RWA', 'Rwanda', '', '', NULL, NULL),
	('SAU', 'Saudi Arabia', '', '', NULL, NULL),
	('SDN', 'Sudan', '', '', NULL, NULL),
	('SEN', 'Senegal', '', '', NULL, NULL),
	('SGP', 'Singapore', '', '', NULL, NULL),
	('SGS', 'South Georgia and the South Sandwich Islands', '', '', NULL, NULL),
	('SHN', 'Saint Helena', '', '', NULL, NULL),
	('SJM', 'Svalbard', '', '', NULL, NULL),
	('SLB', 'Solomon Islands', '', '', NULL, NULL),
	('SLE', 'Sierra Leone', '', '', NULL, NULL),
	('SLV', 'El Salvador', '', '', NULL, NULL),
	('SMR', 'San Marino', '', '', NULL, NULL),
	('SOM', 'Somalia', '', '', NULL, NULL),
	('SPM', 'Saint Pierre and Miquelon', '', '', NULL, NULL),
	('SRB', 'Serbia', '', '', NULL, NULL),
	('SSD', 'South Sudan', '', '', NULL, NULL),
	('STP', 'Sao Tome and Principe', '', '', NULL, NULL),
	('SUR', 'Suriname', '', '', NULL, NULL),
	('SVK', 'Slovakia', '', '', NULL, NULL),
	('SVN', 'Slovenia', '', '', NULL, NULL),
	('SWE', 'Sweden', '', '', NULL, NULL),
	('SWZ', 'Eswatini', '', '', NULL, NULL),
	('SXM', 'Sint Maarten (Dutch part)', '', '', NULL, NULL),
	('SYC', 'Seychelles', '', '', NULL, NULL),
	('SYR', 'Syria', '', '', NULL, NULL),
	('TCA', 'Turks and Caicos Islands', '', '', NULL, NULL),
	('TCD', 'Chad', '', '', NULL, NULL),
	('TGO', 'Togo', '', '', NULL, NULL),
	('THA', 'Thailand', '', '', NULL, NULL),
	('TJK', 'Tajikistan', '', '', NULL, NULL),
	('TKL', 'Tokelau', '', '', NULL, NULL),
	('TKM', 'Turkmenistan', '', '', NULL, NULL),
	('TLS', 'East Timor', '', '', NULL, NULL),
	('TON', 'Tonga', '', '', NULL, NULL),
	('TTO', 'Trinidad and Tobago', '', '', NULL, NULL),
	('TUN', 'Tunisia', '', '', NULL, NULL),
	('TUR', 'Turkey', '', '', NULL, NULL),
	('TUV', 'Tuvalu', '', '', NULL, NULL),
	('TWN', 'Taiwan', '', '', NULL, NULL),
	('TZA', 'Tanzania', '', '', NULL, NULL),
	('UGA', 'Uganda', '', '', NULL, NULL),
	('UKR', 'Ukraine', '', '', NULL, NULL),
	('UMI', 'United States Minor Outlying Islands', '', '', NULL, NULL),
	('URY', 'Uruguay', '', '', NULL, NULL),
	('USA', 'United States of America', '', '', NULL, NULL),
	('UZB', 'Uzbekistan', '', '', NULL, NULL),
	('VAT', 'Holy See', '', '', NULL, NULL),
	('VCT', 'Saint Vincent and the Grenadines', '', '', NULL, NULL),
	('VEN', 'Venezuela', '', '', NULL, NULL),
	('VGB', 'British Virgin Islands', '', '', NULL, NULL),
	('VIR', 'United States Virgin Islands', '', '', NULL, NULL),
	('VNM', 'Vietnam', '', '', NULL, NULL),
	('VUT', 'Vanuatu', '', '', NULL, NULL),
	('WLF', 'Wallis and Futuna', '', '', NULL, NULL),
	('WSM', 'Samoa', '', '', NULL, NULL),
	('YEM', 'Yemen', '', '', NULL, NULL),
	('ZAF', 'South Africa', '', '', NULL, NULL),
	('ZMB', 'Zambia', '', '', NULL, NULL),
	('ZWE', 'Zimbabwe', '', '', NULL, NULL);








