library(shiny)
library(leaflet)
library(DT)
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(shinyjs)
library(rgdal)
#library(rjson)
source('data.R')

indicators<-load_indicators(NULL) 
unique_years <- unique(indicators$year)
years <- as.numeric(unlist(unique_years))
